# Generated by Django 3.2.13 on 2022-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade2',
            field=models.IntegerField(choices=[(5, 'A'), (4, 'B'), (3, 'C'), (2, 'D'), (1, 'E')], default=1),
            preserve_default=False,
        ),
    ]
