# Generated by Django 3.2.13 on 2022-10-07 14:51

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0002_review_grade2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade2',
            field=models.IntegerField(choices=[(5, 'A'), (4, 'B'), (3, 'C'), (2, 'D'), (1, 'E')], default=re.RegexFlag['ASCII']),
        ),
    ]
