# Generated by Django 3.2.13 on 2022-10-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0003_alter_review_grade2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='garde',
        ),
    ]
